// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: pairing.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct Pairing_OuterMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var protocolVersion: UInt32 {
    get {_protocolVersion ?? 0}
    set {_protocolVersion = newValue}
  }
  /// Returns true if `protocolVersion` has been explicitly set.
  var hasProtocolVersion: Bool {self._protocolVersion != nil}
  /// Clears the value of `protocolVersion`. Subsequent reads from it will return its default value.
  mutating func clearProtocolVersion() {self._protocolVersion = nil}

  var status: Pairing_OuterMessage.Status {
    get {_status ?? .ok}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  var hasStatus: Bool {self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  mutating func clearStatus() {self._status = nil}

  var pairingRequest: Pairing_PairingRequest {
    get {_pairingRequest ?? Pairing_PairingRequest()}
    set {_pairingRequest = newValue}
  }
  /// Returns true if `pairingRequest` has been explicitly set.
  var hasPairingRequest: Bool {self._pairingRequest != nil}
  /// Clears the value of `pairingRequest`. Subsequent reads from it will return its default value.
  mutating func clearPairingRequest() {self._pairingRequest = nil}

  var pairingRequestAck: Pairing_PairingRequestAck {
    get {_pairingRequestAck ?? Pairing_PairingRequestAck()}
    set {_pairingRequestAck = newValue}
  }
  /// Returns true if `pairingRequestAck` has been explicitly set.
  var hasPairingRequestAck: Bool {self._pairingRequestAck != nil}
  /// Clears the value of `pairingRequestAck`. Subsequent reads from it will return its default value.
  mutating func clearPairingRequestAck() {self._pairingRequestAck = nil}

  var options: Pairing_Options {
    get {_options ?? Pairing_Options()}
    set {_options = newValue}
  }
  /// Returns true if `options` has been explicitly set.
  var hasOptions: Bool {self._options != nil}
  /// Clears the value of `options`. Subsequent reads from it will return its default value.
  mutating func clearOptions() {self._options = nil}

  var configuration: Pairing_Configuration {
    get {_configuration ?? Pairing_Configuration()}
    set {_configuration = newValue}
  }
  /// Returns true if `configuration` has been explicitly set.
  var hasConfiguration: Bool {self._configuration != nil}
  /// Clears the value of `configuration`. Subsequent reads from it will return its default value.
  mutating func clearConfiguration() {self._configuration = nil}

  var configurationAck: Pairing_ConfigurationAck {
    get {_configurationAck ?? Pairing_ConfigurationAck()}
    set {_configurationAck = newValue}
  }
  /// Returns true if `configurationAck` has been explicitly set.
  var hasConfigurationAck: Bool {self._configurationAck != nil}
  /// Clears the value of `configurationAck`. Subsequent reads from it will return its default value.
  mutating func clearConfigurationAck() {self._configurationAck = nil}

  var secret: Pairing_Secret {
    get {_secret ?? Pairing_Secret()}
    set {_secret = newValue}
  }
  /// Returns true if `secret` has been explicitly set.
  var hasSecret: Bool {self._secret != nil}
  /// Clears the value of `secret`. Subsequent reads from it will return its default value.
  mutating func clearSecret() {self._secret = nil}

  var secretAck: Pairing_SecretAck {
    get {_secretAck ?? Pairing_SecretAck()}
    set {_secretAck = newValue}
  }
  /// Returns true if `secretAck` has been explicitly set.
  var hasSecretAck: Bool {self._secretAck != nil}
  /// Clears the value of `secretAck`. Subsequent reads from it will return its default value.
  mutating func clearSecretAck() {self._secretAck = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum Status: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case ok = 200
    case error = 400
    case badConfiguration = 401
    case badSecret = 402

    init() {
      self = .ok
    }

  }

  init() {}

  fileprivate var _protocolVersion: UInt32? = nil
  fileprivate var _status: Pairing_OuterMessage.Status? = nil
  fileprivate var _pairingRequest: Pairing_PairingRequest? = nil
  fileprivate var _pairingRequestAck: Pairing_PairingRequestAck? = nil
  fileprivate var _options: Pairing_Options? = nil
  fileprivate var _configuration: Pairing_Configuration? = nil
  fileprivate var _configurationAck: Pairing_ConfigurationAck? = nil
  fileprivate var _secret: Pairing_Secret? = nil
  fileprivate var _secretAck: Pairing_SecretAck? = nil
}

nonisolated struct Pairing_PairingRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var serviceName: String {
    get {_serviceName ?? String()}
    set {_serviceName = newValue}
  }
  /// Returns true if `serviceName` has been explicitly set.
  var hasServiceName: Bool {self._serviceName != nil}
  /// Clears the value of `serviceName`. Subsequent reads from it will return its default value.
  mutating func clearServiceName() {self._serviceName = nil}

  var clientName: String {
    get {_clientName ?? String()}
    set {_clientName = newValue}
  }
  /// Returns true if `clientName` has been explicitly set.
  var hasClientName: Bool {self._clientName != nil}
  /// Clears the value of `clientName`. Subsequent reads from it will return its default value.
  mutating func clearClientName() {self._clientName = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _serviceName: String? = nil
  fileprivate var _clientName: String? = nil
}

nonisolated struct Pairing_PairingRequestAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var serverName: String {
    get {_serverName ?? String()}
    set {_serverName = newValue}
  }
  /// Returns true if `serverName` has been explicitly set.
  var hasServerName: Bool {self._serverName != nil}
  /// Clears the value of `serverName`. Subsequent reads from it will return its default value.
  mutating func clearServerName() {self._serverName = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _serverName: String? = nil
}

nonisolated struct Pairing_Options: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var inputEncodings: [Pairing_Options.Encoding] = []

  var outputEncodings: [Pairing_Options.Encoding] = []

  var preferredRole: Pairing_Options.RoleType {
    get {_preferredRole ?? .unknown}
    set {_preferredRole = newValue}
  }
  /// Returns true if `preferredRole` has been explicitly set.
  var hasPreferredRole: Bool {self._preferredRole != nil}
  /// Clears the value of `preferredRole`. Subsequent reads from it will return its default value.
  mutating func clearPreferredRole() {self._preferredRole = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum RoleType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case unknown = 0
    case input = 1
    case output = 2

    init() {
      self = .unknown
    }

  }

  nonisolated struct Encoding: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var type: Pairing_Options.Encoding.EncodingType {
      get {_type ?? .unknown}
      set {_type = newValue}
    }
    /// Returns true if `type` has been explicitly set.
    var hasType: Bool {self._type != nil}
    /// Clears the value of `type`. Subsequent reads from it will return its default value.
    mutating func clearType() {self._type = nil}

    var symbolLength: UInt32 {
      get {_symbolLength ?? 0}
      set {_symbolLength = newValue}
    }
    /// Returns true if `symbolLength` has been explicitly set.
    var hasSymbolLength: Bool {self._symbolLength != nil}
    /// Clears the value of `symbolLength`. Subsequent reads from it will return its default value.
    mutating func clearSymbolLength() {self._symbolLength = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    nonisolated enum EncodingType: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
      case unknown = 0
      case alphanumeric = 1
      case numeric = 2
      case hexadecimal = 3
      case qrcode = 4

      init() {
        self = .unknown
      }

    }

    init() {}

    fileprivate var _type: Pairing_Options.Encoding.EncodingType? = nil
    fileprivate var _symbolLength: UInt32? = nil
  }

  init() {}

  fileprivate var _preferredRole: Pairing_Options.RoleType? = nil
}

nonisolated struct Pairing_Configuration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var encoding: Pairing_Options.Encoding {
    get {_encoding ?? Pairing_Options.Encoding()}
    set {_encoding = newValue}
  }
  /// Returns true if `encoding` has been explicitly set.
  var hasEncoding: Bool {self._encoding != nil}
  /// Clears the value of `encoding`. Subsequent reads from it will return its default value.
  mutating func clearEncoding() {self._encoding = nil}

  var clientRole: Pairing_Options.RoleType {
    get {_clientRole ?? .unknown}
    set {_clientRole = newValue}
  }
  /// Returns true if `clientRole` has been explicitly set.
  var hasClientRole: Bool {self._clientRole != nil}
  /// Clears the value of `clientRole`. Subsequent reads from it will return its default value.
  mutating func clearClientRole() {self._clientRole = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _encoding: Pairing_Options.Encoding? = nil
  fileprivate var _clientRole: Pairing_Options.RoleType? = nil
}

nonisolated struct Pairing_ConfigurationAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct Pairing_Secret: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var secret: Data {
    get {_secret ?? Data()}
    set {_secret = newValue}
  }
  /// Returns true if `secret` has been explicitly set.
  var hasSecret: Bool {self._secret != nil}
  /// Clears the value of `secret`. Subsequent reads from it will return its default value.
  mutating func clearSecret() {self._secret = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _secret: Data? = nil
}

nonisolated struct Pairing_SecretAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var secret: Data {
    get {_secret ?? Data()}
    set {_secret = newValue}
  }
  /// Returns true if `secret` has been explicitly set.
  var hasSecret: Bool {self._secret != nil}
  /// Clears the value of `secret`. Subsequent reads from it will return its default value.
  mutating func clearSecret() {self._secret = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _secret: Data? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "pairing"

nonisolated extension Pairing_OuterMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OuterMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}protocol_version\0\u{1}status\0\u{4}\u{8}pairing_request\0\u{3}pairing_request_ack\0\u{2}\u{9}options\0\u{2}\u{a}configuration\0\u{3}configuration_ack\0\u{2}\u{9}secret\0\u{3}secret_ack\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self._protocolVersion) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._status) }()
      case 10: try { try decoder.decodeSingularMessageField(value: &self._pairingRequest) }()
      case 11: try { try decoder.decodeSingularMessageField(value: &self._pairingRequestAck) }()
      case 20: try { try decoder.decodeSingularMessageField(value: &self._options) }()
      case 30: try { try decoder.decodeSingularMessageField(value: &self._configuration) }()
      case 31: try { try decoder.decodeSingularMessageField(value: &self._configurationAck) }()
      case 40: try { try decoder.decodeSingularMessageField(value: &self._secret) }()
      case 41: try { try decoder.decodeSingularMessageField(value: &self._secretAck) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._protocolVersion {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._status {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._pairingRequest {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._pairingRequestAck {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._options {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    } }()
    try { if let v = self._configuration {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 30)
    } }()
    try { if let v = self._configurationAck {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 31)
    } }()
    try { if let v = self._secret {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 40)
    } }()
    try { if let v = self._secretAck {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 41)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_OuterMessage, rhs: Pairing_OuterMessage) -> Bool {
    if lhs._protocolVersion != rhs._protocolVersion {return false}
    if lhs._status != rhs._status {return false}
    if lhs._pairingRequest != rhs._pairingRequest {return false}
    if lhs._pairingRequestAck != rhs._pairingRequestAck {return false}
    if lhs._options != rhs._options {return false}
    if lhs._configuration != rhs._configuration {return false}
    if lhs._configurationAck != rhs._configurationAck {return false}
    if lhs._secret != rhs._secret {return false}
    if lhs._secretAck != rhs._secretAck {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Pairing_OuterMessage.Status: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}H\u{3}STATUS_OK\0\u{2}H\u{3}STATUS_ERROR\0\u{1}STATUS_BAD_CONFIGURATION\0\u{1}STATUS_BAD_SECRET\0")
}

nonisolated extension Pairing_PairingRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PairingRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}service_name\0\u{3}client_name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._serviceName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._clientName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._serviceName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._clientName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_PairingRequest, rhs: Pairing_PairingRequest) -> Bool {
    if lhs._serviceName != rhs._serviceName {return false}
    if lhs._clientName != rhs._clientName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Pairing_PairingRequestAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".PairingRequestAck"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}server_name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._serverName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._serverName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_PairingRequestAck, rhs: Pairing_PairingRequestAck) -> Bool {
    if lhs._serverName != rhs._serverName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Pairing_Options: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Options"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}input_encodings\0\u{3}output_encodings\0\u{3}preferred_role\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.inputEncodings) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.outputEncodings) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._preferredRole) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.inputEncodings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.inputEncodings, fieldNumber: 1)
    }
    if !self.outputEncodings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.outputEncodings, fieldNumber: 2)
    }
    try { if let v = self._preferredRole {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_Options, rhs: Pairing_Options) -> Bool {
    if lhs.inputEncodings != rhs.inputEncodings {return false}
    if lhs.outputEncodings != rhs.outputEncodings {return false}
    if lhs._preferredRole != rhs._preferredRole {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Pairing_Options.RoleType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ROLE_TYPE_UNKNOWN\0\u{1}ROLE_TYPE_INPUT\0\u{1}ROLE_TYPE_OUTPUT\0")
}

nonisolated extension Pairing_Options.Encoding: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Pairing_Options.protoMessageName + ".Encoding"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{3}symbol_length\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._type) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._symbolLength) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._type {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._symbolLength {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_Options.Encoding, rhs: Pairing_Options.Encoding) -> Bool {
    if lhs._type != rhs._type {return false}
    if lhs._symbolLength != rhs._symbolLength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Pairing_Options.Encoding.EncodingType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ENCODING_TYPE_UNKNOWN\0\u{1}ENCODING_TYPE_ALPHANUMERIC\0\u{1}ENCODING_TYPE_NUMERIC\0\u{1}ENCODING_TYPE_HEXADECIMAL\0\u{1}ENCODING_TYPE_QRCODE\0")
}

nonisolated extension Pairing_Configuration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Configuration"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}encoding\0\u{3}client_role\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._encoding) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._clientRole) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._encoding {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._clientRole {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_Configuration, rhs: Pairing_Configuration) -> Bool {
    if lhs._encoding != rhs._encoding {return false}
    if lhs._clientRole != rhs._clientRole {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Pairing_ConfigurationAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ConfigurationAck"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_ConfigurationAck, rhs: Pairing_ConfigurationAck) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Pairing_Secret: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Secret"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}secret\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._secret) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._secret {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_Secret, rhs: Pairing_Secret) -> Bool {
    if lhs._secret != rhs._secret {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Pairing_SecretAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SecretAck"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}secret\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self._secret) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._secret {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Pairing_SecretAck, rhs: Pairing_SecretAck) -> Bool {
    if lhs._secret != rhs._secret {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
